version: '2.0'
services:
  postgresql:
    image: postgres:15.1

    environment:
      - POSTGRES_USER=pavlick
      - POSTGRES_PASSWORD=pavlick
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: on-failure