CREATE TABLE cryptocurrency
(
    id                               bigserial primary key,
    created                          TIMESTAMP,
    updated                          TIMESTAMP,
    status                           VARCHAR(10),
    circulating_supply               bigint,
    cmc_rank                         bigint,
    date_added                       timestamp(6),
    fully_diluted_market_cap_fiat    numeric(38, 2),
    id_api                           bigint,
    is_active                        bigint,
    is_fiat                          varchar(255),
    last_updated                     timestamp(6),
    last_updated_fiat                timestamp(6),
    market_cap_dominance_fiat        numeric(38, 2),
    market_cap_fiat                  numeric(38, 2),
    max_supply                       bigint,
    name                             varchar(255),
    num_market_pairs                 bigint,
    percent_change1h_fiat            numeric(38, 2),
    percent_change24h_fiat           numeric(38, 2),
    percent_change30d_fiat           numeric(38, 2),
    percent_change7d_fiat            numeric(38, 2),
    platform_id                      bigint,
    platform_name                    varchar(255),
    platform_slug                    varchar(255),
    platform_symbol                  varchar(255),
    platform_token_address           varchar(255),
    price_fiat                       numeric(38, 2),
    self_reported_circulating_supply varchar(255),
    self_reported_market_cap         varchar(255),
    slug                             varchar(255),
    symbol                           varchar(255),
    tags                             jsonb,
    total_supply                     bigint,
    volume24h_fiat                   numeric(38, 2),
    volume_change24h_fiat            numeric(38, 2)
);

CREATE TABLE users
(
    id                     bigserial primary key,
    created                TIMESTAMP,
    updated                TIMESTAMP,
    status                 VARCHAR(10),
    username               VARCHAR(56),
    first_name             varchar(100),
    last_name              varchar(100),
    email                  varchar(100),
    password               VARCHAR(100),
    fiat_currency          BIGINT,
    role                   varchar(15),
    birthday_date          timestamp,
    country                varchar(154),
    fiat_currency_symbol   varchar(10),
    crypto_currency        BIGINT,
    crypto_currency_symbol varchar(10)

);
